### ISSUE TITLE
새로운 기능 추가해주세요.

### ISSUE THREAD

**Issue by ddyokim** [taeguk/auto-lecture-evaluation#6]
교수님께 3점을 드린다는 것은 정말 슬픈 일입니다.
하지만 3점을 주고싶어하는 학생들도 있을 수 있으니, 평가의 기준을 상, 중, 하로 나누어서 기준에 따라 랜덤하게 체크가 될 수 있도록 기능을 추가해주세요.
상(4~5점 랜덤)
중(3~5점 랜덤)
하(2~5점 랜덤)
1점은 우리 모두 주지 맙시다...

**Comment by ddyokim** [comment]
range를 정해서 줄 수 있는 기능을 추가해주시면 좋을 것 같습니다.

**Comment by taeguk** [comment]
이미 있습니다! 아이콘을 누르면 노란배경에 글자들이 나오죠? 거기보면 설정이 있습니다. 그거 누르면 범위를 설정할 수 있습니다.

**Comment by ddyokim** [comment]
에에 그러 크롬 확장프로그램에서도 업데이트 된 사항인가요? 왜 저는 발견하지 못했죠? 캡쳐로 알려주세요ㅠㅠ

**Comment by taeguk** [comment]
![image](https://cloud.githubusercontent.com/assets/9107889/19887892/90496754-a06e-11e6-9f5f-66fbdddb4d9b.png)
설정 창 요깃어요!
